service: cvbaby-images

package:
  artifact: package.zip

plugins:
  - serverless-offline

custom:
  serverless-offline:
      port: 3002

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${opt:stage, "dev"}
  environment: ${file(./config.${opt:stage, "dev"}.json)}
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::${self:provider.environment.CVBABY_BUCKET_POST}
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::${self:provider.environment.CVBABY_BUCKET_POST}/*

functions:
  processImage:
    handler: handler.processImage
    events:
      - http:
          path: /processImage
          method: post
