service: cvbaby-pdf

plugins:
  - serverless-offline

custom:
  serverless-offline:
      port: 3003

package:
  artifact: ./package.zip

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 1600
  region: us-east-1
  stage: ${opt:stage, "local"}
  environment: ${file(./config.${opt:stage, "local"}.json)}
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::${self:provider.environment.CVBABY_HOST_DATA}
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::${self:provider.environment.CVBABY_HOST_DATA}/*

functions: ${file(functions-${opt:stage, "local"}.yml)}
