version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/

# For deployments to Amazon Linux, Ubuntu Server, or RHEL instances,
#   you can specify a "permissions"
#   section here that describes special permissions to apply to the files
#   in the "files" section as they are being copied over to
#   the Amazon EC2 instance.
# permissions:
#   - object:
#     pattern:
#     except:
#     owner:
#     group:
#     mode:
#     acls:
#       -
#     context:
#       user:
#       type:
#       range:
#     type:
#       -

hooks:
  ApplicationStop:
    - location: /stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /build.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /start.sh
      timeout: 300
      runas: root